ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: linziqiaolzq/quickstart-appsmith
DockerComposeEnvPath: .env
RegionId: ap-southeast-1
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
Owner: linziqiaolzq
Branch: main
Platform: github
